lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'  #Lo que hace es buscar la variable  con el mismo nombre en el .env
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 2600000
