App\Entity\Categoria:
  attributes:
    id:
      groups: ['get_categorias', 'post_categoria', 'get_categoria', 'update_categoria']

    categoria:
      groups: ['get_categorias', 'post_categoria', 'get_categoria', 'update_categoria']