App\Entity\Categoria:
  attributes:
    id:
      groups: ['get_categorias', 'post_categoria', 'get_categoria', 'update_categoria', 'get_restaurante' , 'res_filtered']

    categoria:
      groups: ['get_categorias', 'post_categoria', 'get_categoria', 'update_categoria', 'get_restaurante' , 'res_filtered']